version: "3.9"
services:
  web:
    build: .
    ports:
      - "80:80"
    environment:
      - AOC_YEAR
      - AOC_LEADERBOARD_ID
      - AOC_SESSION_COOKIE
    volumes:
      - ./files:/var/www/html